# Required cluster role to allow spire-server to query k8s API server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-server-cluster-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - get
      - create
---
# Role for the SPIRE server
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spire-server-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - trust-bundle
    resources:
      - configmaps
    verbs:
      - get
      - patch
---
