# Required cluster role to allow spire-server to query k8s API server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.roles.clusterRole.name }}
  namespace: {{ .Values.namespace }}
rules:
{{ .Values.roles.clusterRole.rules | toYaml | indent 4 }}
---
# Role for the SPIRE server
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.roles.role.name }}
rules:
{{ .Values.roles.role.rules | toYaml | indent 2 }}
---
