# Default values for spire-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: spire
name: spire-server
serviceAccount: spire-server
trustDomain: "cluster.local"
clusterName: demo-cluster
replicas: 2
images:
  spireServer:
    image: gcr.io/spiffe-io/spire-server:1.4.1
    imagePullPolicy: "IfNotPresent"
  spireControllerManager:
    image: ghcr.io/spiffe/spire-controller-manager:0.2.1
    imagePullPolicy: "IfNotPresent"

configmaps:
  notifier:
    bundleName: trust-bundle
  serverConfig:
    bindAddress: "0.0.0.0"
    bindPort: "8081"
    socketPath: "/run/spire/sockets/api.sock"
    trustDomain: "cluster.local"
    dataDir: "/run/spire/server/data"
    logLevel: "DEBUG"
    caKeyType: "rsa-4096"
    defaultSvidTTL: "1h"

    federates: false
    federation:
        bundleEndpoint:
          address: "0.0.0.0"
          port: "8443"
          withAcme: false
          acme:
            directoryUrl: ""
            domainName: ""
            email: ""
            tosAccepted: ""
        federations:
          - federatesWith: "domain.test"
            bundleEndpointUrl: "https://192.168.0.16:4002"
            bundleEndpointProfile:
              profile: "https_spiffe"
              endpointSpiffeId: "spiffe://domain.test/spire/server"

    caSubject:
      country: "US"
      organization: "SPIFFE"
      commonName: ""

    plugins:
      dataStore: "sql"
      pluginData:
        dataBaseType: "sqlite3"
        connectionString: "/run/spire/data/datastore.sqlite3"

    nodeAttestor:
      attestor: "k8s_psat"
      pluginData:
        clusters:
          - clusterName: "demo-cluster"
            useTokenReviewApiValidation: "true"
            serviceAccountAllowList: "spire:spire-agent"

    keyManager:
      type: "disk"
      pluginData:
        keysPath: "/run/spire/data/keys.json"

    notifier:
      type: "k8sbundle"
      configMap: "trust-bundle"
      configMapKey: "root-cert.pem"

    healthChecks:
      listenerEnabled: true
      bindAddress: "0.0.0.0"
      bindPort: "8080"
      livePath: "/live"
      readyPath: "/ready"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# services
serviceSpire:
  type: NodePort
  ports:
   - name: api
     port: 8081
     targetPort: 8081
     protocol: TCP
serviceBundleEndpoint:
  name: spire-server-bundle-endpoint
  type: NodePort
  ports:
    - name: api
      port: 8443
      protocol: TCP
serviceControllerWebhook:
  name: spire-controller-manager-webhook-service
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443

resources:
  requests:
    storage: "1Gi"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

roles:
  clusterRole:
    name: spire-server-cluster-role
    rules:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: [ "get" ]
      - apiGroups: [ "authentication.k8s.io" ]
        resources: [ "tokenreviews" ]
        verbs: [ "get", "create" ]
  clusterRoleBinding:
    name: spire-server-cluster-role-binding
    subjects:
      - kind: ServiceAccount
        name: spire-server
        namespace: spire
    roleRef:
      kind: ClusterRole
      name: spire-server-cluster-role
      apiGroup: rbac.authorization.k8s.io
  role:
    name: spire-server-role
    rules:
      - apiGroups: [ "" ]
        resources: [ "pods" ]
        verbs: [ "get" ]
      - apiGroups: [ "" ]
        resources: [ "configmaps" ]
        resourceNames: [ "trust-bundle" ]
        verbs: [ "get", "patch" ]
  roleBinding:
    name: spire-server-role-binding
    subjects:
      - kind: ServiceAccount
        name: spire-server
        namespace: spire
    roleRef:
      kind: Role
      name: spire-server-role
      apiGroup: rbac.authorization.k8s.io